# Generated by Django 3.1.5 on 2021-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('evangelico', models.BooleanField(default=False)),
                ('igreja', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=150)),
            ],
        ),
    ]
