# Generated by Django 3.1.5 on 2021-01-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Participantes'),
        ),
    ]
