# Generated by Django 3.1.5 on 2021-01-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcao', '0001_initial'),
        ('participantes', '0003_auto_20210115_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcao.funcao'),
        ),
    ]
