# Generated by Django 3.1.5 on 2021-01-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0004_auto_20210115_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='funcao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
