# Generated by Django 3.1.5 on 2021-01-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0006_auto_20210115_1929'),
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='lider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lider_equipe', to='participantes.participante'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(null=True, related_name='membros_equipe', to='participantes.Participante'),
        ),
    ]
